# Import

In [1]:
import numpy as np
from scipy.linalg import lu
from scipy.linalg import lu_factor, lu_solve

# LU Decomposition

In [4]:
A = np.array([[2, 1, 1], [4, -6, 0], [-2, 7, 2]])
b = np.array([5, -2, 9])

In [8]:
A.shape[0]

3

In [10]:
np.zeros_like(A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [12]:
def lu_decomp(A):
    n = A.shape[0]
    L = np.zeros_like(A)
    U = np.zeros_like(A)

    for i in range(n):
        for k in range(i, n):
            U[i, k] = A[i, k] - sum(L[i, j] * U[j, k] for j in range(i))

        for k in range(i, n):
            if i == k:
                L[i, i] = 1
            else:
                L[k, i] = (A[k, i] - sum(L[k, j] * U[j, i] for j in range(i))) / U[i, i]
    return L, U

In [14]:
L, U = lu_decomp(A)

L, U

(array([[ 1,  0,  0],
        [ 2,  1,  0],
        [-1, -1,  1]]),
 array([[ 2,  1,  1],
        [ 0, -8, -2],
        [ 0,  0,  1]]))

In [16]:
y = np.linalg.solve(L, b) 

x = np.linalg.solve(U, y)

x

array([1., 1., 2.])

In [18]:
lu, p = lu_factor(A)

lu, p

(array([[ 4. , -6. ,  0. ],
        [ 0.5,  4. ,  1. ],
        [-0.5,  1. ,  1. ]]),
 array([1, 1, 2], dtype=int32))

In [20]:
x = lu_solve((lu, p), b)
x

array([1., 1., 2.])

# QR Decomposition

In [22]:
A = np.array([[1, 1], [1, -1], [1, 1]])
A

array([[ 1,  1],
       [ 1, -1],
       [ 1,  1]])

In [25]:
def qr_decomp(A):
    #1
    a1 = A[:, 0]
    Q1 = a1 / np.linalg.norm(a1)

    #2
    a2 = A[:, 1]
    proj = (np.dot(a2, Q1) / np.dot(Q1, Q1)) * Q1
    v2 = a2 - proj
    Q2 = v2 / np.linalg.norm(v2)

    #Q
    Q = np.column_stack((Q1, Q2))
    # print(Q)

    #R
    R = np.dot(Q.T, A)

    return Q, R

In [27]:
qr_decomp(A)

[[ 0.57735027  0.40824829]
 [ 0.57735027 -0.81649658]
 [ 0.57735027  0.40824829]]


(array([[ 0.57735027,  0.40824829],
        [ 0.57735027, -0.81649658],
        [ 0.57735027,  0.40824829]]),
 array([[ 1.73205081e+00,  5.77350269e-01],
        [-1.11022302e-16,  1.63299316e+00]]))

# Eigenvalue and Eigenvector Decomposition

In [29]:
A = np.array([[4, 1], [2, 3]])

In [31]:
eigenvalue, eigenvector = np.linalg.eig(A)

eigenvalue, eigenvector

(array([5., 2.]),
 array([[ 0.70710678, -0.4472136 ],
        [ 0.70710678,  0.89442719]]))