# Libraries

In [1]:
import numpy as np

from scipy.sparse import csr_matrix

# Section01

## 1.1 Definition of a Vector and Notation

In [3]:
v = np.array([0.2, -0.7, 0.5, 1.2])

v

array([ 0.2, -0.7,  0.5,  1.2])

In [5]:
type(v)

numpy.ndarray

## 1.2 Unit Vectors

In [7]:
def unit_vector(v):
    norm = np.linalg.norm(v)
    return v / norm

In [9]:
v = np.array([3, -4, 5])

u = unit_vector(v)

u

array([ 0.42426407, -0.56568542,  0.70710678])

## 1.3 Addition and Subtraction of Vectors

In [11]:
a = np.array([2, 3, 1])
b = np.array([5, -1, 4])

In [13]:
print(a, b)

[2 3 1] [ 5 -1  4]


In [15]:
add = a + b

In [17]:
add

array([7, 2, 5])

In [19]:
sub = a-b
sub

array([-3,  4, -3])

## 1.4 Scalar Multiplication

In [21]:
v = np.array([1.5, -3, 4])
scalar = 2.5

r = scalar * v

r

array([ 3.75, -7.5 , 10.  ])

## 1.5 Norm of a Vector

In [23]:
v

array([ 1.5, -3. ,  4. ])

In [25]:
np.linalg.norm(v)

5.220153254455275

In [27]:
np.linalg.norm([1, -2, 2, -3])

4.242640687119285

## 1.6 Dot Product

In [29]:
a = np.array([2, 3, -1])
b = np.array([4, -1, 5])

np.dot(a, b) #ort

0

In [31]:
A = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]]) #3x3   #3x2   #3x2

B = np.array([[1, 2],
             [4, 5],
             [7, 8]])

In [33]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
B

array([[1, 2],
       [4, 5],
       [7, 8]])

In [37]:
np.dot(A, B)

array([[ 30,  36],
       [ 66,  81],
       [102, 126]])

In [39]:
1 + 8 + 21

30

In [41]:
C = np.array([[1, 2],
             [4, 5],
             [7, 8]]) #3x2 #3x2 

In [43]:
np.dot(B, C)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [47]:
np.dot(B, C.T)

array([[  5,  14,  23],
       [ 14,  41,  68],
       [ 23,  68, 113]])

In [49]:
C.T

array([[1, 4, 7],
       [2, 5, 8]])

## 1.7 Angle Between Two Vectors and Its Applications in Machine Learning

In [51]:
def cosine_sim(a, b):
    dot_prod = np.dot(a, b)
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)
    return dot_prod / (norm_a * norm_b)

In [53]:
a = np.array([3, -5])
b = np.array([7, 1])

In [55]:
cos_theta = cosine_sim(a, b)

In [57]:
cos_theta

0.38805700005813276

In [61]:
theta = np.degrees(np.arccos(cos_theta))

In [63]:
theta

67.16634582208245

# Section02

## 2.1 Identity Matrix

In [65]:
I = np.eye(3)

In [67]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
r = np.dot(A, I)
r

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [73]:
# A . I = A

## 2.2 Non-Zero Matrix

In [75]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 2.3 Sparse Matrix

In [77]:
S = csr_matrix([[3, 0, 0], [0, 0, 0], [0, 0, 0]])
S

<Compressed Sparse Row sparse matrix of dtype 'int32'
	with 1 stored elements and shape (3, 3)>

In [81]:
S.toarray()

array([[3, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## 2.4,5,6 Singular & Non-singular Matrix & Inverse 

In [83]:
matrix_1 = np.array([[2, 4],
                     [1, 2]])

matrix_2 = np.array([[1, 2],
                     [3, 4]])

In [85]:
det1 = np.linalg.det(matrix_1)

In [87]:
det1

0.0

In [89]:
det2 = np.linalg.det(matrix_2)
det2

-2.0000000000000004

In [91]:
print(f"M1 is {'Sing' if det1 == 0 else 'non-sing'}")

M1 is Sing


In [93]:
print(f"M2 is {'Sing' if det2 == 0 else 'non-sing'}")

M2 is non-sing


In [95]:
np.linalg.inv(matrix_1)

LinAlgError: Singular matrix

In [97]:
np.linalg.inv(matrix_2)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## 2.7 Diagonal Matrix

In [99]:
D = np.diag([3, 5, 7])
D

array([[3, 0, 0],
       [0, 5, 0],
       [0, 0, 7]])

In [101]:
matrix_1 = np.array([[3, 0, 0],
                     [0, 5, 0],
                     [0, 0, 7]])

matrix_2 = np.array([[1, 2, 0],
                     [0, 5, 0],
                     [0, 0, 9]])

In [107]:
def is_diag(M):
    return np.all(M == np.diag(np.diagonal(M)))

In [109]:
is_diag(matrix_1)

True

In [111]:
is_diag(matrix_2)

False

## 2.2 Symmetric Matrix

In [117]:
matrix = np.array([[1, 2, 3],
                   [2, 5, 6],
                   [3, 6, 9]])

In [119]:
np.array_equal(matrix, matrix.T)

True

In [121]:
m = np.array([[1, 2, 3],
                   [2, 5, -1],
                   [3, 6, 9]])

In [123]:
np.array_equal(m, m.T)

False

# Section03

## 3.1 Calculate Matrix Rank

In [113]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [115]:
rank_A = np.linalg.matrix_rank(A)

rank_A

2